/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gregory Shcherbakov (https://sketchfab.com/gostarts)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/handpaint-girl-02-cdfeae7eca514999a7bf00e639852d1f
title: Handpaint - Girl 02
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/scene.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    /* highlight-line */
    actions['idle'].play(); /* highlight-line */
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="43ab42863eb14c64a8e7a917b3f1f801fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.02}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_10" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_12" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_14" rotation={[-Math.PI / 2, 0, 0]} />
                  <group
                    name="girl01girl01_grp_geo"
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <group name="girl01girl01_eyes_geo" />
                    <group name="girl01girl01_bodyup_geo" />
                    <group name="girl01girl01_bodydwn_geo" />
                    <group name="girl01girl01_hair_geo" />
                    <group name="girl01girl01_head_geo" />
                  </group>
                  <group
                    name="platform1"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={115}
                  >
                    <mesh
                      name="platform1_platform_0"
                      geometry={nodes.platform1_platform_0.geometry}
                      material={materials.platform}
                    />
                  </group>
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.girl01girl01_eyes_albedo}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.girl01girl01_bodyup_albedo}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.girl01girl01_bodydwn_albedo}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.girl01girl01_hair_albedo}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials.girl01girl01_head_albedo}
                    skeleton={nodes.Object_15.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
